### ISSUE TITLE
Biberfreunde/ Dokumente archivieren  - Fehlermeldung (PH)

### ISSUE THREAD

**Issue by PinkieTester** [AlexanderPraegla/Pinkie#10]
FF 20:32 admin

wollte bei den Biberfreunden eigentlich die verknüpften Dokumente löschen - was ja nicht angeboten wird. Dann habe ich auf archivieren gedrückt  - beim ersten ging alles gut, jetzt kommt die Fehlermeldung 

Error 500 - Internal Server Error
Es ist ein internet Fehler aufgetreten
javax.servlet.ServletException

Und die Seite lässt sich über die Navi auch nciht mehr aufrufen.

**Comment by AlexanderPraegla** [comment]
Die Fehlermeldung liegt an einer NPE welche auftritt, wenn keine Dokumente mehr vorhanden sind

**Comment by AlexanderPraegla** [comment]
Fixed
