### ISSUE TITLE
Ankündigungen  (PH)

### ISSUE THREAD

**Issue by PinkieTester** [AlexanderPraegla/Pinkie#12]
Ich würde den Block  'News' oder 'Aktuelles' nennen - sind ja nicht unbedingt nur Ankündigungen.

Dann habe ich eine Neue erstellt und ein Bild eingefügt, das nur als Download dort angebunden wird. Find ich irgendwie komisch - würde es eher als 20% oder so in die News direkt auf die home packen, falls platztechnisch möglich.

Mir fehlt hier auch ein Datum, von wann die News ist.
Würde auch nur die drei letzten anzeigen, dann evtl. einen Link auf ein Archiv.
was das Archivieren ist, ist mir unklar, wollte ich nicht ausprobieren, nachdem das ARchivieren von den Dokumenten (siehe #10) nicht funktioniert hat.

**Comment by AlexanderPraegla** [comment]
Ich würde das mit dem Bild zur Ankündung erstmal hinten anstellen. Ich hab ein neues Issue erstellt, damit es nicht untergeht ([zum Issue](https://github.com/AlexanderPraegla/Pinkie/issues/30))
