### ISSUE TITLE
Home - Elemente (PH)

### ISSUE THREAD

**Issue by PinkieTester** [AlexanderPraegla/Pinkie#13]
Ankündigungen siehe #12 im Detail

Es sollten hier die Spielberichte (als box) ebenfalls zu finden sein. oder muss dann für jeden Spielbericht eine news erstellt werden mit Link dahin?
Oder wie ist das angedacht ?
Empfehlung : es gibt eine Extrabox darunter auch mit den drei letzten Berichten und dann einen Link zur Übersichtsseite unter Aktuelles

**Comment by AlexanderPraegla** [comment]
Neues Element für die letzten 5 Berichte hinzugefügt (können wir je nach dem auch noch ändern aber ich denke mehr als 5 macht keinen Sinn). Übers Design lässt sich streiten, bei Vorschlägen ändere ich noch gerne was, sonst fällt mir aber nichts ein wie es besser aussehen könnte (Entwickler eben 😉 )
