### ISSUE TITLE
Layout home (PH)

### ISSUE THREAD

**Issue by PinkieTester** [AlexanderPraegla/Pinkie#14]
Bild oben - wenn hier das Biber logo wieder rein soll, dann Bilddaten zusenden

Box. Ankündigung:  schöner wäre es die einzelnen Ankündigung in der Box ohne Rahmen darzustellen  und dafür das Datum davor zu schreiben , somit wäre ebenfalls eine Struktur zu erkennen.

**Comment by AlexanderPraegla** [comment]
Rahmen um Ankündigungsbox entfernt und Datum hinzugefügt
