### ISSUE TITLE
Bilder / Dokumente  (PH)

### ISSUE THREAD

**Issue by PinkieTester** [AlexanderPraegla/Pinkie#15]
mir ist noch nicht ganz klar, wie ich in manchen Anwendungsfällen Bilder am besten hochlade (Format), dann evtl. wieder löschen kann oder aktualisieren.
Das gleiche Thema bei Dokumenten - z.b. was es bedeutet zu archivieren, welche Auswirkungen dies hat. 
Gibt es eine generelle Übersicht aller Dokumente ? Oder ist das nicht gewünscht gewesen?

Denke Trainer oder wer auch immer hier 'editieren' darf , müssen eine kurze Anleitung bekommen, was sie wie machen können.

**Comment by AlexanderPraegla** [comment]
Hier würde ich ein Dropdown von allen Dokumenten (nur von der bestimmten Kategorie?) machen

**Comment by AlexanderPraegla** [comment]
ich werde wenn die neue Homepage live geht den Trainern vorher eine kurze Einweisung geben, wie sie berichte hochladen können, ihr Mannschaft pflegen, etc.
