### ISSUE TITLE
Damen 1

### ISSUE THREAD

**Issue by dorisbreuer** [AlexanderPraegla/Pinkie#151]
Bei den Damen 1 ist auf einmal die TABELLE und der Spielplan futsch....
kannst du wieder einfügen? Bitte

**Comment by AlexanderPraegla** [comment]
Das ist das gleiche Problem wie bei den Herren 1. Da stimmt irgendwas mit
der Schnittstelle zur nuLiga nicht. Muss ich mir mal anschauen wenn Zeit
ist..

Am Di., 3. Sept. 2019 um 20:58 Uhr schrieb dorisbreuer <
notifications@github.com>:

**Comment by dorisbreuer** [comment]
Alex - am kommenden WE fängt die Saison an. Da wäre es gut wenn die Sachen bei den Herren und Damen gefixt ist........Bitte
