### ISSUE TITLE
Archivieren...

### ISSUE THREAD

**Issue by PinkieTester** [AlexanderPraegla/Pinkie#21]
Wenn man ein Startbild archiviert. Taucht es unter Ankündigungen wieder auf. 
Gibt es auch die Möglichkeit, archiviert rückgängig machen... ist aus meiner sicht nice to have..

**Comment by AlexanderPraegla** [comment]
Den Bug kann ich nicht bestätigen.

Zum archivieren: ich warte mal auf Feedback ob es wirklich gewünscht ist sowas rückgängig machen zu wollen
