### ISSUE TITLE
Förderverein aktualisieren

### ISSUE THREAD

**Issue by Pfeife** [AlexanderPraegla/Pinkie#51]
Es gab dieses Jahr Neuwahlen beim Förderverein, Benny ist geblieben, stellvertretende Vorsitzende: Katharina Künstner (Handball), Kassier: Robert Fischbacher (Fußball), Schriftführerin: Katharina Hauk (Turnen und Tanz).

**Comment by AlexanderPraegla** [comment]
Erledigt
