### ISSUE TITLE
Über uns  (inhaltlich)  (PH)

### ISSUE THREAD

**Issue by PinkieTester** [AlexanderPraegla/Pinkie#9]
da ja nur die Unterpunkte sich anklicken lassen - nicht die main navigation, würde ich noch einen Punkt einfügen

Jugendarbeit    - hier ein bisschen Text zum Jugendkonzept - wieviele Trainer, was während des Jahres den Jugendmanschaften angeboten wird (Inzell, Trainingslager, Turniere wie in Südtirol, Hollland )   
wieviele Mannschaften, Spieler, wieviel Trainer mit Lizenz ... )   

Geschichte :   tabellarischer Aufstellung, keinen Fließtext

**Comment by AlexanderPraegla** [comment]
Hab ne neue Seite für die Jugendarbeit erstellt - Muss aber mit Text befüllt werden.

Die Geschichte wird jetzt in Form eines Zeitstrahl dargestellt
